# Generated by Django 4.0.5 on 2022-06-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0002_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('specification', models.CharField(blank=True, max_length=50, null=True)),
                ('available_time', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=50, null=True)),
                ('clinic_city', models.CharField(blank=True, max_length=50, null=True)),
                ('clinic_address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyapp.user')),
            ],
        ),
    ]
