# Generated by Django 4.0.5 on 2022-06-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0005_alter_user_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user_id',
            new_name='User_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user_id',
            new_name='User_id',
        ),
    ]
