# Generated by Django 4.0.5 on 2022-06-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0007_doctor_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pic',
            field=models.FileField(default='media/pet.jpg', upload_to='media/images'),
        ),
    ]
